---
- name: Update apt repo/cache
  become: true
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade packages
  apt: upgrade=yes force_apt_get=yes
  become: true

- name: Install packages
  become: true
  package:
    name:
      - snapd
      - netcat-traditional
      - python3-pip
      - python3-venv
    state: latest