---
- name: Install nginx
  become: true
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Copy nginx configuration
  become: true
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Remove default nginx page
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx